spring:
  datasource:
    url: jdbc:mysql://localhost:3306/awesome-spring-transactions
    username: root
    password: my-secret-pw
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #show-sql: true
    #properties:
    #  hibernate:
    #    format_sql: true
logging:
  level:
    org.springframework.orm.jpa: DEBUG # jpa log
    org.springframework.transaction: DEBUG # transactional log
